### ISSUE TITLE
Data corruption possible because some right-shift operators are incorrectly ported

### ISSUE THREAD

**Issue by ssb22** [ahmedihafez/primers-java#1]
The C version of PrimerPooler uses unsigned integers to represent all bit patterns, which means the right-shift operator `>>` always brings in `0` bits on the left.

The Java language has no unsigned integers, so we must change all instances of the right-shift operator `>>` into `>>>` so as to explicitly specify that it should be a logical right-shift, not an arithmetic right-shift.  If `>>` is used instead of `>>>`, and if there is a `1` bit in the leftmost position of the operand, then a new `1` will be added to the bit pattern, and this can corrupt our data in some cases.

In most cases the port is correctly using `>>>`, but there are still instances in `PoolSplit.java` and `primers64/DegeneratePrimer64.java` where `>>` is used.  I have not done a full analysis of exactly which circumstances would cause this to corrupt data, so I suggest after fixing it we inform users that they should re-run their calculations in the new version, because the first version might have given them inaccurate results due to this bit-pattern corruption.

**Comment by ahmedihafez** [comment]
Many thanks for your help, I have replaced it, And This will be merged to the next updated of the app.

**Comment by ssb22** [comment]
Does the 2021-11-02 version of the app have this fix?  I'm guessing not, because it still ships with `primers-java_1.0.0.202010270704.jar` with files dated 27th October 2020, which was before the fix was committed on 2nd November 2020.

**Comment by ahmedihafez** [comment]
Hi @ssb22 , It should be, The latest build of the package is ```primers-java_1.0.0.202102051119.jar```.
Can you let me know Which build version of the SeqEditor application do you have?, You can find this from the main menu (Help -> About SeqEditor) ?

**Comment by ssb22** [comment]
Thanks, I downloaded the 2021-11-02 versions of SeqEditor from https://gpro.biotechvana.com/download/SeqEditor (all 3 platforms), and all 3 zip files contain `primers-java_1.0.0.202010270704.jar`, not `primers-java_1.0.0.202102051119.jar`.  Maybe they still have an old version of the package by mistake?

**Comment by ahmedihafez** [comment]
Many thanks for your feedback, yes you are right, there is a problem with it, I will check and fix it. 
I will inform you once it is updated.

**Comment by ssb22** [comment]
Thanks, the 2021-11-19 downloads have `primers-java_1.0.0.202102051119.jar` with the fixed code.

**Comment by ahmedihafez** [comment]
> Thanks, the 2021-11-19 downloads have `primers-java_1.0.0.202102051119.jar` with the fixed code.

Thanks for your feedback, Let me know if you have any other issue with the app.
