### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by ssb22** [ahmedihafez/primers-java#13]
Technically we're not supposed to use package names from domains we do not control, for example `pooler.org` currently directs to a domain-parking company, somebody could buy it and claim we're using their domain.

I've been told I can use `*.ssb22.ucam.org` in perpetuity, so I suppose it makes sense to use `org.ucam.ssb22.pooler` instead of `org.pooler` throughout.  The code that calls it will also have to use the new package name.

**Comment by ahmedihafez** [comment]
```org.ucam.ssb22.pooler``` would be fine, I will update everything accordingly.
